services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: citaapp-backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend-admin:
    build:
      context: .
      dockerfile: frontend/admin/Dockerfile
    container_name: citaapp-admin
    ports:
      - "8081:80" # Acceso en http://localhost:8081

  frontend-customer:
    build:
      context: .
      dockerfile: frontend/customer/Dockerfile
    container_name: citaapp-customer
    ports:
      - "8082:80" # Acceso en http://localhost:8082

volumes:
  pgdata: